# Generated by Django 5.1.3 on 2025-06-07 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='month',
            field=models.CharField(default='January', max_length=20),
        ),
    ]
