# Generated by Django 5.1.3 on 2025-06-17 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0005_remove_expenses_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='month',
            field=models.IntegerField(default=6),
        ),
    ]
