# Generated by Django 5.1.3 on 2025-06-17 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0006_expenses_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenses',
            name='month',
        ),
    ]
