# Generated by Django 5.1.3 on 2025-06-01 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loging',
            name='password',
            field=models.CharField(max_length=20),
        ),
    ]
