# Generated by Django 5.1.3 on 2025-06-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loging', '0002_alter_loging_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('que', models.TextField()),
                ('ans', models.TextField()),
            ],
        ),
    ]
