# Generated by Django 5.1.3 on 2025-06-09 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loging', '0003_flashcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pomodoro_Timer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
            ],
        ),
    ]
