# Generated by Django 5.1.3 on 2025-06-09 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loging', '0004_pomodoro_timer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pomodoro_timer',
            name='time',
            field=models.TimeField(default=30),
        ),
    ]
