# Generated by Django 5.1.3 on 2025-06-12 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loging', '0005_alter_pomodoro_timer_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pomodoro_timer',
            name='time',
            field=models.IntegerField(default=30),
        ),
    ]
