# Generated by Django 5.1.3 on 2025-06-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loging', '0006_alter_pomodoro_timer_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contect_email', models.EmailField(max_length=254)),
                ('massage', models.TextField()),
            ],
        ),
    ]
