# Generated by Django 5.1.3 on 2025-06-16 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loging', '0007_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='massage',
            new_name='message',
        ),
    ]
