# Generated by Django 5.1.3 on 2025-06-16 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loging', '0008_rename_massage_contact_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='help',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField()),
                ('ans', models.TextField()),
            ],
        ),
    ]
