# Generated by Django 5.1.3 on 2025-06-17 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loging', '0009_help'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loging',
            name='email',
        ),
        migrations.AddField(
            model_name='loging',
            name='user_name',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
