# Generated by Django 5.1.3 on 2025-06-03 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='attendance',
            new_name='attendances',
        ),
    ]
