# Generated by Django 5.1.3 on 2025-06-08 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_rename_attendance_attendances'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendances',
            name='pcls',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attendances',
            name='tcls',
            field=models.IntegerField(default=0),
        ),
    ]
