# Generated by Django 5.1.3 on 2025-06-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planner',
            name='task',
            field=models.CharField(max_length=100),
        ),
    ]
