# Generated by Django 5.1.3 on 2025-06-03 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_alter_planner_task'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='planner',
            new_name='plannerdt',
        ),
    ]
